/**
 * LittleSparks — Import Processed PDF Content into Seed
 *
 * Reads the reviewed lesson-content.json and writes a new seed content file.
 * Run AFTER reviewing scripts/output/lesson-content.json.
 *
 * Usage:
 *   npx tsx scripts/import-pdf-content.ts
 *
 * Output: prisma/seed-vedic-content.ts
 *   This file exports lesson/quiz data that prisma/seed.ts can import.
 */

import fs from "fs";
import path from "path";

const INPUT_FILE = path.join(process.cwd(), "scripts", "output", "lesson-content.json");
const OUTPUT_FILE = path.join(process.cwd(), "prisma", "seed-vedic-content.ts");

interface QuizQuestion {
  text: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  order: number;
}

interface ProcessedLesson {
  suggestedTitle: string;
  suggestedSlug: string;
  suggestedModule: number;
  duration: number;
  starsReward: number;
  content: { blocks: unknown[] };
}

interface ProcessedModule {
  moduleNumber: number;
  moduleTitle: string;
  lessons: ProcessedLesson[];
  quiz: {
    title: string;
    questions: QuizQuestion[];
  };
}

interface ProcessedOutput {
  modules: ProcessedModule[];
}

function main() {
  if (!fs.existsSync(INPUT_FILE)) {
    console.error(`❌ Input file not found: ${INPUT_FILE}`);
    console.error("   Run process-pdf-content.ts first.");
    process.exit(1);
  }

  const data = JSON.parse(fs.readFileSync(INPUT_FILE, "utf-8")) as ProcessedOutput;

  let output = `/**
 * AUTO-GENERATED by scripts/import-pdf-content.ts
 * Source: vedic maths book.pdf (processed via Claude AI)
 * Review and adjust before using in production seed.
 *
 * Usage in prisma/seed.ts:
 *   import { VEDIC_MODULES } from "./seed-vedic-content";
 */

export const VEDIC_MODULES = ${JSON.stringify(data.modules, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, output);

  console.log("✅ Seed content written to:", OUTPUT_FILE);
  console.log(`   ${data.modules.length} modules`);
  console.log(
    `   ${data.modules.reduce((sum, m) => sum + m.lessons.length, 0)} total lessons`
  );
  console.log(
    `   ${data.modules.reduce((sum, m) => sum + m.quiz.questions.length, 0)} total quiz questions`
  );
  console.log("\nNext: import VEDIC_MODULES in prisma/seed.ts and use it to create lessons.");
}

main();
